export const THEMACOLOR = '#98a39d';

export const ACT_LOAD_PROFILE = 'ACT_LOAD_PROFILE';
export const ACT_LOAD_LOCAL_DIARY = 'ACT_LOAD_LOCAL_DIARY';
export const ACT_MOCK_LOCAL = 'ACT_MOCK_LOCAL';

export const ACT_API_FETCH_DUCK_LIST = 'ACT_API_FETCH_DUCK_LIST';
export const ACT_FETCH_DUCK_LIST = 'ACT_FETCH_DUCK_LIST';
export const ACT_CLEAR_DUCK_LIST = 'ACT_CLEAR_DUCK_LIST';

export const ACT_ADD_DUCK_TO_WISHLIST = 'ACT_ADD_DUCK_TO_WISHLIST';
export const ACT_LOAD_WISHLIST = 'ACT_LOAD_WISHLIST';
export const ACT_REMOVE_WISHLIST = 'ACT_REMOVE_WISHLIST';
export const ACT_CLEAR_WISHLISH_MSG = 'ACT_CLEAR_WISHLISH_MSG';
export const ACT_DISPLAY_WISHLISH_MSG = 'ACT_DISPLAY_WISHLISH_MSG';

export const ACT_ADD_DUCK = 'ACT_ADD_DUCK';


export const ACT_LOAD_DIARY = 'ACT_LOAD_DIARY';
export const ACT_LOAD_DUCK_DIARY = 'ACT_LOAD_DUCK_DIARY';
export const ACT_ADD_DIARY = 'ACT_ADD_DIARY';

export const ACT_SHARE_DUCK = 'ACT_SHARE_DUCK';
export const ACT_API_SHARE_DUCK_RES = 'ACT_API_SHARE_DUCK_RES';
export const ACT_API_SHARE_DUCK_CLEAR_MSG = 'ACT_API_SHARE_DUCK_CLEAR_MSG';


export const ACT_API_LOGIN = 'ACT_API_LOGIN';
export const ACT_LOGIN_RES = 'ACT_LOGIN_RES';
export const ACT_CLEAR_LOGIN = 'ACT_CLEAR_LOGIN';
